//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlTest___Patient
    {
        public int bltp_id { get; set; }
        public int bltp_patid { get; set; }
        public int bltp_testid { get; set; }
        public System.DateTime bltp_date { get; set; }
        public int bltp_state { get; set; }
    
        public virtual BloodTest BloodTest { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual State State { get; set; }
    }
}
