//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult___Patient
    {
        public int cp_id { get; set; }
        public int cp_patid { get; set; }
        public int cp_consid { get; set; }
        public System.DateTime cp_date { get; set; }
        public int cp_state { get; set; }
    
        public virtual State State { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Consultation Consultation { get; set; }
    }
}
