//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HepaticTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HepaticTest()
        {
            this.HepTest___Patient = new HashSet<HepTest___Patient>();
        }
    
        public int heptest_id { get; set; }
        public Nullable<double> heptest_bilir { get; set; }
        public Nullable<int> heptest_timil { get; set; }
        public Nullable<double> heptest_alt { get; set; }
        public Nullable<double> heptest_ast { get; set; }
        public Nullable<int> heptest_uricasid { get; set; }
        public Nullable<double> heptest_kreat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HepTest___Patient> HepTest___Patient { get; set; }
    }
}
