//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HepTest___Patient
    {
        public int htp_id { get; set; }
        public int htp_patid { get; set; }
        public int htp_testid { get; set; }
        public System.DateTime htp_date { get; set; }
        public int htp_state { get; set; }
    
        public virtual HepaticTest HepaticTest { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual State State { get; set; }
    }
}
