//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TubDataBaseEntities : DbContext
    {
        public TubDataBaseEntities()
            : base("name=TubDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BK> BK { get; set; }
        public virtual DbSet<BloodTest> BloodTest { get; set; }
        public virtual DbSet<BlTest___Patient> BlTest___Patient { get; set; }
        public virtual DbSet<Consult___Patient> Consult___Patient { get; set; }
        public virtual DbSet<Consultation> Consultation { get; set; }
        public virtual DbSet<ConsultationType> ConsultationType { get; set; }
        public virtual DbSet<Destruction> Destruction { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<HepaticTest> HepaticTest { get; set; }
        public virtual DbSet<HepTest___Patient> HepTest___Patient { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<SputumTest> SputumTest { get; set; }
        public virtual DbSet<SputumTest___Patient> SputumTest___Patient { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<UrineTest> UrineTest { get; set; }
        public virtual DbSet<UrTest__Patient> UrTest__Patient { get; set; }
    }
}
