//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrineTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrineTest()
        {
            this.UrTest__Patient = new HashSet<UrTest__Patient>();
        }
    
        public int urtest_id { get; set; }
        public Nullable<double> urtest_protein { get; set; }
        public string urtest_sugar { get; set; }
        public Nullable<int> urtest_leumin { get; set; }
        public Nullable<int> urtest_leumax { get; set; }
        public Nullable<int> urtest_ermin { get; set; }
        public Nullable<int> urtest_ermax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrTest__Patient> UrTest__Patient { get; set; }
    }
}
